# =========================
# Build stage
# =========================
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build

WORKDIR /src

# Copy the entire PharmacyPOS folder
COPY . .

# Restore solution
RUN dotnet restore PharmacyPOS.sln

# Publish API
RUN dotnet publish PharmacyPOS.API/PharmacyPOS.API.csproj \
    -c Release \
    -o /app/publish \
    --no-restore


# =========================
# Runtime stage
# =========================
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS final

WORKDIR /app

# Copy published API
COPY --from=build /app/publish .

# Render uses port 10000
ENV ASPNETCORE_URLS=http://+:10000

EXPOSE 10000

# Start API
ENTRYPOINT ["dotnet", "PharmacyPOS.API.dll"]
