name: .NET API CI

on:
  workflow_dispatch:

  push:
    branches:
      - main
    paths:
      - 'PharmacyPOS/**'

  pull_request:
    branches:
      - main
    paths:
      - 'PharmacyPOS/**'

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: PharmacyPOS

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore PharmacyPOS.sln

      - name: Build
        run: dotnet build PharmacyPOS.sln --configuration Release --no-restore

      - name: Test
        run: dotnet test PharmacyPOS.sln --configuration Release --no-build
